### ISSUE TITLE
RT not working

### ISSUE THREAD

**Issue by kyokill** [redpeacock78/tw-search-retweet-bot#2]
# Overview / RT component not working in run.yml
# Objective / Fix RT run
# Proposal Details / 
Errors when running the run.yml workfile - see attached images comparing when it was working vs current (not working). It appears to be having errors when trying to run github action during the process.
![image](https://user-images.githubusercontent.com/120657726/211983005-f7b2a0ba-8e4b-4e04-80d6-c59aa7872edd.png)
![image](https://user-images.githubusercontent.com/120657726/211983018-acb82644-8018-456a-a4fd-1bb5a84728e3.png)

Thank you for investigating!

# Tasks / タスク
- [ ] If it can be broken down into smaller tasks, write them down / 細かいタスクに分解できているなら書き出す

# Overview / 概要
# Reproduction Procedure / 再現手順
# How do we get in trouble if we don't fix it? / 修正しないとどう困るか
# Cause / 原因
# Amendments / 修正案

**Comment by redpeacock78** [comment]
```yml
      - name: Judge SEARCH_LIMIT
        if: ${{ steps.running_count.outputs.result == '1' }}
        id: search_limit
        run: |
            default="${{ secrets.SEARCH_LIMIT }}"
            echo "{value}=${default:-100}" >> $GITHUB_OUTPUT
```
https://github.com/kyokill/tw-search-retweet-bot/blob/e5de4399aef85539d29e3e9f4da3e66f8496530e/.github/workflows/run.yml#L47-L52

The error seems to be due to the fact that the number that should be passed to the Python side does not contain the expected value.
If this is the case, the value that is passed to Python from the outside is an environment variable that specifies the upper limit of the number of searches, so I suspect that the above is the problem.

**Comment by redpeacock78** [comment]
I found a tool to easily replace Deprecated set-env, set-output, etc. in GitHub Actions, so I documented [it](https://github.com/azu/set-env-to-github_env).
This is what it looks like as far as comparing the Before & After here.
- Before
  ```yml
  - name: set env for prod
     if: github.ref == 'refs/heads/main'
     run: |
       echo "::set-env name=FILE_ID::${FILE_ID}"
       echo "::set-env name=BUCKET_NAME::${BUCKET_NAME}"
  ```
- After
  ```yml
  - name: set env for prod
     if: github.ref == 'refs/heads/main'
     run: |
       echo "FILE_ID=${FILE_ID}" >> $GITHUB_ENV
       echo "BUCKET_NAME=${BUCKET_NAME}" >> $GITHUB_ENV
  ```
---
Then this one will be from this state
https://github.com/redpeacock78/tw-search-retweet-bot/blob/03f3b6963eeb46539e6d568e4f303a4dba5d586d/.github/workflows/run.yml#L47-L52
so this is the state of affairs
```yml
      - name: Judge SEARCH_LIMIT
        if: ${{ steps.running_count.outputs.result == '1' }}
        id: search_limit
        run: |
            default="${{ secrets.SEARCH_LIMIT }}"
            echo "{value}=${default:-100}" >> $GITHUB_OUTPUT
```
https://github.com/kyokill/tw-search-retweet-bot/blob/e5de4399aef85539d29e3e9f4da3e66f8496530e/.github/workflows/run.yml#L47-L52
It is presumed that the following conditions are desirable.
```yml
      - name: Judge SEARCH_LIMIT
        if: ${{ steps.running_count.outputs.result == '1' }}
        id: search_limit
        run: |
            default="${{ secrets.SEARCH_LIMIT }}"
            echo "value=${default:-100}" >> $GITHUB_OUTPUT
```
